export const state = {
  products:    [],
  collections: [],
  cart:        JSON.parse(localStorage.getItem('elisee:cart') || '[]'),
  wishlist:    JSON.parse(localStorage.getItem('elisee:wish') || '[]'),
  screen:      'home',
  prevScreen:  null,
  activeProduct: null,
  activeVariant:  null,
  activeOptions:  {},
  searchQuery:    '',
  sortOption:     '',
  wishFilter:     false,
  selectedCol:    'all',
  quizStep:       0,
  quizAnswers:    {},
  pageInfo:       { hasNextPage: false, endCursor: null },
  isLoadingMore:  false,
};
